steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/ghostinthearchive/ghostinthearchive/pipelines:latest', '-f', 'Dockerfile.jobs', '.']
images:
  - 'asia-northeast1-docker.pkg.dev/ghostinthearchive/ghostinthearchive/pipelines:latest'
