services:
  curator:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    command: ["curator_server.py"]
    ports:
      - "8001:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=ghostinthearchive
      - GOOGLE_GENAI_USE_VERTEXAI=TRUE
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/adc.json
      - FIRESTORE_EMULATOR_HOST=
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/tmp/keys/adc.json:ro
