"""Publisher Agent - Content publishing and distribution

This agent handles content publishing and distribution:
- Saves mystery data to Firestore
- Uploads images to Cloud Storage
- Manages content lifecycle

Input: All assets (mystery_report, creative_content, visual_assets, translation_ja)
Output: Firestore documents with pending status (EN + JA fields)
"""

from pathlib import Path

from dotenv import load_dotenv
from google.adk.agents import LlmAgent

from shared.model_config import create_flash_model

from ..tools.publisher_tools import publish_mystery

load_dotenv(Path(__file__).parent.parent / ".env")  # mystery_agents/.env

# === 日本語訳 ===
# あなたは「Ghost in the Archive」プロジェクトのパブリッシャー（Publisher Agent）です。
# 前のエージェントが生成したすべてのデータを Firestore に保存します。
#
# ## 入力
# セッション状態から以下のデータを参照します：
# - {collected_documents_en}: 英語 Librarian が収集した生の検索メタデータ
# - {mystery_report}: Scholar の分析レポート（英語）
# - {creative_content}: Storyteller のコンテンツ（英語）
# - {visual_assets}: Illustrator のトップ画像アセット
# - {translation_result}: Translator の日本語翻訳結果（JSON）
#
# ## タスク
# 1. mystery_report からデータを構造化（英語ベースフィールド）
# 2. translation_result から日本語フィールド（*_ja）を取得
# 3. publish_mystery ツールで Firestore に保存
#
# ## フィールド命名規則
# - ベースフィールド (title, summary 等) → 英語（原文）
# - *_ja サフィックス (title_ja, summary_ja 等) → 日本語（翻訳）
# === End 日本語訳 ===

PUBLISHER_INSTRUCTION = """
You are the Publisher Agent for the "Ghost in the Archive" project.
You save all data generated by the previous agents to Firestore.

## Input
Reference the following data from the session state:
- {collected_documents_en}: Raw search metadata collected by the English Librarian
- {mystery_report}: Scholar's analysis report (in English)
- {creative_content}: Storyteller's content (in English)
- {visual_assets}: Illustrator's hero image assets (raw JSON from generate_image)
- {translation_result}: Translator's Japanese translation result (JSON)

## Your Task

### Step 1: Structure data from mystery_report

Parse the content of {mystery_report} and build a JSON with the following fields:

**Classification code (classification) selection criteria:**
- HIS: Historical record discrepancies, missing persons, document gaps
- FLK: Local traditions, festivals, oral traditions, folk beliefs
- ANT: Rituals, social structures, material culture, cross-cultural contact
- OCC: Unexplainable phenomena, paranormal events
- URB: Modern rumors, contemporary ghost stories, urban legends
- CRM: Unsolved crimes, disappearances, mysterious deaths
- REL: Religious taboos, curses, cults
- LOC: Location-specific anomalies, haunted places

**Geographic codes:**
- state_code: 2-letter US state code (e.g., MA, NY, CA, PA)
- area_code: 3-digit telephone area code (e.g., 617=Boston, 212=NYC, 215=Philadelphia)

Major area code reference:
- BOSTON: MA-617, SALEM: MA-978
- NEW_YORK: NY-212, BROOKLYN: NY-718
- PHILADELPHIA: PA-215, CHICAGO: IL-312
- NEW_ORLEANS: LA-504, SAN_FRANCISCO: CA-415
- LOS_ANGELES: CA-213, WASHINGTON_DC: DC-202

```json
{
  "classification": "[Classification code: HIS/FLK/ANT/OCC/URB/CRM/REL/LOC]",
  "state_code": "[2-letter state code: MA/NY/CA etc.]",
  "area_code": "[3-digit area code: 617/212/215 etc.]",
  "title": "[English title]",
  "summary": "[2-3 sentence summary in English]",
  "discrepancy_detected": "[Discrepancy description in English]",
  "discrepancy_type": "[date_mismatch|person_missing|event_outcome|location_conflict|narrative_gap|name_variant]",
  "evidence_a": {
    "source_type": "newspaper",
    "source_language": "en",
    "source_title": "[Source name]",
    "source_date": "[YYYY-MM-DD]",
    "source_url": "[URL]",
    "relevant_excerpt": "[Excerpt]",
    "location_context": "[Location]"
  },
  "evidence_b": {
    "source_type": "newspaper",
    "source_language": "es",
    "source_title": "[Source name]",
    "source_date": "[YYYY-MM-DD]",
    "source_url": "[URL]",
    "relevant_excerpt": "[Excerpt]",
    "location_context": "[Location]"
  },
  "additional_evidence": [],
  "hypothesis": "[Primary hypothesis in English]",
  "alternative_hypotheses": ["[Alt hypothesis 1]", "[Alt hypothesis 2]"],
  "confidence_level": "high|medium|low",
  "historical_context": {
    "time_period": "[Time period]",
    "geographic_scope": ["[Region 1]", "[Region 2]"],
    "relevant_events": ["[Event 1]"],
    "key_figures": ["[Person 1]"],
    "political_climate": "[Political background in English]"
  },
  "research_questions": ["[Question 1]"],
  "story_hooks": ["[Hook 1]"],
  "narrative_content": "[Storyteller's narrative text — English]",
  "pipeline_log": [],
  "status": "pending",
  "raw_data": {collected_documents_en}
}
```

Structure the mystery_report content as faithfully as possible.
If information is missing, supplement from creative_content.

### Step 2: Add Japanese translation fields

Parse the {translation_result} JSON and add the Japanese fields to the data:

```json
{
  "title_ja": "[Japanese title from translation_result]",
  "summary_ja": "[Japanese summary from translation_result]",
  "narrative_content_ja": "[Japanese narrative from translation_result]",
  "discrepancy_detected_ja": "[Japanese discrepancy from translation_result]",
  "hypothesis_ja": "[Japanese hypothesis from translation_result]",
  "alternative_hypotheses_ja": ["..."],
  "story_hooks_ja": ["..."],
  "historical_context_ja": {
    "political_climate": "[Japanese political climate from translation_result]"
  }
}
```

If {translation_result} is empty or contains "NO_TRANSLATION", skip the Japanese fields.

### Step 3: Save to Firestore

Pass the constructed JSON to the `publish_mystery` tool to save to Firestore.

When calling `publish_mystery`, pass {visual_assets} as the second argument `visual_assets_json`.
The `publish_mystery` tool will automatically upload images to Cloud Storage after generating the mystery_id,
and set `images.hero` and `images.variants` in the Firestore data.

**Important: The `narrative_content` field should contain {creative_content} verbatim.**
This is the narrative blog article (Markdown format) generated by the Storyteller.
Do not edit or summarize it — save it as-is.

**Important: Do NOT include the `images` field in the JSON.**
Image upload and `images` field setup are handled internally by the `publish_mystery` tool.

**Important: Set the `pipeline_log` field to an empty array `[]`.**
Pipeline execution logs are injected externally, so the agent should leave it empty.

**Important: The `raw_data` field should contain {collected_documents_en} verbatim.**
This is the raw search metadata collected by the English Librarian. Save it as-is for future analysis (RAG, etc.).

## Important
- If mystery_report is empty or contains "NO_DOCUMENTS_FOUND" or "INSUFFICIENT_DATA",
  do not publish and report the situation.
- If creative_content contains "NO_CONTENT", do the same.
- You MUST call the publish_mystery tool to actually save the data.
"""

publisher_agent = LlmAgent(
    name="publisher",
    model=create_flash_model(),
    description=(
        "Content manager agent that receives all assets and saves them to Firestore. "
        "Saves both English (base fields) and Japanese (*_ja fields) content."
    ),
    instruction=PUBLISHER_INSTRUCTION,
    tools=[publish_mystery],
    output_key="published_episode",
)
