import { Archive, ExternalLink } from "lucide-react"

export function Footer() {
  return (
    <footer className="border-t border-border/50 bg-card/50 mt-auto">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Brand */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Archive className="w-5 h-5 text-gold" />
              <span className="font-serif text-parchment">Ghost in the Archive</span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AI-powered excavation of historical mysteries and folkloric anomalies from public digital archives.
            </p>
            <p className="text-xs text-muted-foreground font-jp">
              AI がアーカイブの闇から発掘する、歴史の亡霊たち
            </p>
          </div>

          {/* Sources */}
          <div className="space-y-4">
            <h3 className="text-sm font-mono uppercase tracking-wider text-parchment">Primary Sources</h3>
            <ul className="space-y-2">
              <li>
                <a
                  href="https://www.loc.gov/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-muted-foreground hover:text-gold transition-colors inline-flex items-center gap-1.5 no-underline"
                >
                  Library of Congress
                  <ExternalLink className="w-3 h-3" />
                </a>
              </li>
              <li>
                <a
                  href="https://dp.la/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-muted-foreground hover:text-gold transition-colors inline-flex items-center gap-1.5 no-underline"
                >
                  Digital Public Library of America
                  <ExternalLink className="w-3 h-3" />
                </a>
              </li>
              <li>
                <a
                  href="https://digitalcollections.nypl.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-muted-foreground hover:text-gold transition-colors inline-flex items-center gap-1.5 no-underline"
                >
                  New York Public Library
                  <ExternalLink className="w-3 h-3" />
                </a>
              </li>
              <li>
                <a
                  href="https://archive.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-muted-foreground hover:text-gold transition-colors inline-flex items-center gap-1.5 no-underline"
                >
                  Internet Archive
                  <ExternalLink className="w-3 h-3" />
                </a>
              </li>
            </ul>
          </div>

          {/* Technical */}
          <div className="space-y-4">
            <h3 className="text-sm font-mono uppercase tracking-wider text-parchment">Technical</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Discoveries generated by AI agents analyzing digitized archival records.
              All source citations link to original documents where available.
            </p>
            <p className="text-xs text-muted-foreground font-mono">
              <span className="redacted">████</span> CLASSIFIED RESEARCH DIVISION <span className="redacted">████</span>
            </p>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="mt-12 pt-6 border-t border-border/30 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-muted-foreground font-mono">
            Document Classification: PUBLIC RELEASE
          </p>
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} Ghost in the Archive Research Initiative
          </p>
        </div>
      </div>
    </footer>
  )
}
